version: 1.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: xai6ZDrD1VHWtJPXBTfhHBfhn2dAKAtajFtuVBuMIDpjj/fLcHb6B5vssYmzZ5X2
before_build:
  - cmd: nuget restore ReCaptcha.NET4.5.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory .\NUnit
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory .\OpenCover
  - nuget install coveralls.net -Version 0.6.0 -OutputDirectory .\coveralls.net
build:
  project: ReCaptcha.NET4.5.sln
  verbosity: minimal
test_script:
  - .\OpenCover\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:".\NUnit\NUnit.ConsoleRunner.3.4.1\tools\nunit3-console.exe" -targetargs:"NET.nunit" -output:coverage.xml -register:user
  - .\coveralls.net\coveralls.net.0.6.0\tools\csmacnz.coveralls.exe --opencover -i .\coverage.xml
